version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/propex-orders-api
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}
    - run:
        name: Gradle Clean
        command: ./gradlew clean
    - run:
        name: Gradle Build
        command: ./gradlew build -DBUILD_NUM=$CIRCLE_BUILD_NUM
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}
    - run:
        name: Install KloudFormation
        command: curl -sSL install.kloudformation.hexlabs.io | bash -s -- -local
    - restore_cache:
        keys:
        - kloudformation-{{ checksum "kloudformation.sh" }}
    - run:
        name: Deploy Stack
        command:  ./kloudformation.sh -m serverless@0.1.6 deploy -stack-name propex-test-stack -location build/libs/propex-orders-api-0.1.$CIRCLE_BUILD_NUM-uber.jar -bucket hexlabs-deployments -key PROPEX.zip
    - save_cache:
        paths:
        - ~/.kloudformation
        key: kloudformation-{{ checksum "kloudformation.sh" }}